services:
  database:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret123
      POSTGRES_DB: vector_db
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
  
  database_migration:
    # image: oceradien/demo-api:latest
    build: .
    depends_on:
      - database
    environment:
      DATABASE_URL: postgressql://postgres:supersecret123@database:5432/vector_db
    command: ["bash", "-c" ,"sleep 10 && bunx drizzle-kit push"]
    restart: "no"